---
output:
  sort-results: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  concurrency: 0
  timeout: 5m
  issues-exit-code: 2
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true

linters:
  disable-all: false
  enable-all: true
  disable:
    # Opting-out
    - nonamedreturns  # named returns are occasionally useful
    - exhaustruct  # does not serve much of a purpose
    - funlen  # not interested
    - cyclop  # not interested much
    - godox  # having these are useful

    # Duplicating
    - gci  # we use go-imports instead

    # Deprecated
    - tenv

linters-settings:
  staticcheck:
    checks:
      - "all"

  depguard:
    rules:
      main:
        files:
          - $all
        allow:
          - $gostd
          - go.farcloser.world
          - github.com/rs/zerolog
          - github.com/rs/zerolog/log
          - go.uber.org/goleak
          - golang.org/x/sync/errgroup
          - golang.org/x/term
          - gotest.tools
