name: "Node"

description: "A compounded action preparing the environment"

inputs:
  go-version:
    required: false
    default: "stable"
    description: ""

runs:
  using: composite
  steps:
    - name: "Install: go"
      uses: ./.github/actions/install-go
      with:
        go-version: ${{ inputs.go-version }}
    - name: "Install: dev-tools"
      uses: ./.github/actions/install-dev-tools
    - name: "Cache: go mod"
      shell: bash
      run: |
        go mod download
        echo "ACTION_NODE_ARCH=$(echo "$RUNNER_ARCH" | sed -E "s/(X86|X64)/amd64/" | sed -E "s/(ARM|ARM64)/arm64/")" >> "$GITHUB_ENV"
        echo "ACTION_NODE_OS=$(echo "$RUNNER_OS" | tr '[:upper:]' '[:lower:]' | sed -E "s/macos/darwin/")" >> "$GITHUB_ENV"
