name: lint

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:

jobs:
  env:
    name: " "
    uses: ./.github/workflows/environment.yml

  lint:
    needs: env
    timeout-minutes: ${{ fromJSON(needs.env.outputs.TIMEOUT_SHORT) }}
    name: lint | go ${{ matrix.go}} | ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ${{ needs.env.outputs.RUNNER_LINUX_STABLE }}
            go: ${{ needs.env.outputs.GO_STABLE }}
          - runner: ${{ needs.env.outputs.RUNNER_LINUX_CANARY }}
            go: ${{ needs.env.outputs.GO_CANARY }}

    steps:
      - name: "Clone"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 100
      - name: "Setup"
        uses: ./.github/actions/node
        with:
          go: ${{ matrix.go }}
      - name: "Linting"
        run: |
          export LINT_COMMIT_RANGE="$(jq -r '.after + "..HEAD"' ${GITHUB_EVENT_PATH})"
          make lint

  test:
    needs: env
    timeout-minutes: ${{ fromJSON(needs.env.outputs.TIMEOUT_SHORT) }}
    name: test | go ${{ matrix.go}} | ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ${{ needs.env.outputs.RUNNER_WINDOWS_STABLE }}
            go: ${{ needs.env.outputs.GO_STABLE }}
          - runner: ${{ needs.env.outputs.RUNNER_MACOS_STABLE }}
            go: ${{ needs.env.outputs.GO_STABLE }}
          - runner: ${{ needs.env.outputs.RUNNER_LINUX_STABLE }}
            go: ${{ needs.env.outputs.GO_STABLE }}
          - runner: ${{ needs.env.outputs.RUNNER_LINUX_CANARY }}
            go: ${{ needs.env.outputs.GO_CANARY }}

    steps:
      - name: "Clone"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 100
      - name: "Install go"
        uses: ./.github/actions/install-go
        with:
          go: ${{ matrix.go }}
      - name: "test-unit"
        run: |
          # Windows does not have gcc - maybe msys2 could be worth looking into
          [ "$RUNNER_OS" == Windows ] || make test-unit
      - name: "test-unit-race"
        run: |
          make test-unit-race
      - name: "test-unit-bench"
        run: |
          make test-unit-bench
