name: test

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-dependencies:
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    name: unit | ${{ matrix.runner }} | ${{ matrix.goversion }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: windows-2022
            goversion: stable
          - runner: macos-14
            goversion: stable
          - runner: ubuntu-24.04
            goversion: stable
          - runner: ubuntu-24.04
            goversion: canary
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: "Install go"
        uses: ./.github/actions/install-go
        with:
          version: ${{ matrix.goversion }}
      - name: "test-unit"
        run: |
          make test-unit
      - name: "test-unit-race"
        run: |
          make test-unit-race
      - name: "test-unit-bench"
        run: |
          make test-unit-bench
